on:
  workflow_dispatch:

name: Knit docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Setup Rmarkdown
        run: |
          Rscript -e 'install.packages("rmarkdown")'
          Rscript -e 'install.packages("distill")'
          Rscript -e 'install.packages("postcards")'

      - name: Render site
        run: Rscript -e 'rmarkdown::render_site()'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs