on:
  workflow_dispatch:

name: Knit docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Render site
        run: |
          docker run --rm \
          --name jensberg047.github.io.builder \
          --volume jensberg047.github.io:/usr/src/app \
          ghcr.io/wilsonify/jensberg047.github.io.builder:main \
          Rscript -e 'rmarkdown::render_site()'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs